#!/bin/bash

set -m

echo "========== Running frontend on port 8000 =============="
echo "========== Running backend on port 5000 =============="
./system_utils/run_frontend.sh &
./system_utils/run_backend.sh
kill %1

